import swaggerJsdoc from 'swagger-jsdoc';

const spec = swaggerJsdoc({
  definition: {
    openapi: '3.0.0',
    info: { title: 'MyTick API', version: '1.1.0', description: 'Task & infrastructure management API' },
    servers: [{ url: '/api' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
        adminKey: { type: 'apiKey', in: 'header', name: 'x-admin-key' },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: { error: { type: 'string' } },
        },
        User: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            email: { type: 'string', format: 'email' },
            username: { type: 'string' },
            name: { type: 'string' },
          },
        },
        AuthResponse: {
          type: 'object',
          properties: {
            token: { type: 'string' },
            user: { $ref: '#/components/schemas/User' },
          },
        },
        Task: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            type: { type: 'string', enum: ['task', 'project'] },
            status: { type: 'string', enum: ['pending', 'in_progress', 'on_hold', 'done', 'abandoned'] },
            visibility: { type: 'string', enum: ['private', 'group', 'public'] },
            groupIds: { type: 'array', items: { type: 'string' } },
            shareToken: { type: 'string' },
            blockedBy: { type: 'array', items: { type: 'string' } },
            parentId: { type: 'string', nullable: true },
            deadline: { type: 'string', format: 'date-time', nullable: true },
            tags: { type: 'array', items: { type: 'string' } },
            pinned: { type: 'boolean' },
            recurrence: {
              type: 'object',
              nullable: true,
              properties: {
                freq: { type: 'string', enum: ['daily', 'weekly', 'monthly', 'yearly'] },
                interval: { type: 'integer' },
                until: { type: 'string', format: 'date-time' },
                count: { type: 'integer' },
                byDay: { type: 'array', items: { type: 'string', enum: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'] } },
              },
            },
            metadata: { type: 'object', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        TaskCreate: {
          type: 'object',
          required: ['title'],
          properties: {
            title: { type: 'string', minLength: 1, maxLength: 500 },
            description: { type: 'string', maxLength: 5000 },
            type: { type: 'string', enum: ['task', 'project'] },
            visibility: { type: 'string', enum: ['private', 'group', 'public'] },
            groupIds: { type: 'array', items: { type: 'string' } },
            blockedBy: { type: 'array', items: { type: 'string' } },
            parentId: { type: 'string', nullable: true },
            deadline: { type: 'string', format: 'date-time', nullable: true },
            recurrence: {
              type: 'object',
              nullable: true,
              properties: {
                freq: { type: 'string', enum: ['daily', 'weekly', 'monthly', 'yearly'] },
                interval: { type: 'integer', minimum: 1 },
                until: { type: 'string', format: 'date-time' },
                count: { type: 'integer', minimum: 1 },
                byDay: { type: 'array', items: { type: 'string', enum: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'] } },
              },
            },
            metadata: { type: 'object', nullable: true },
            tags: { type: 'array', items: { type: 'string' } },
            pinned: { type: 'boolean' },
          },
        },
        TaskUpdate: {
          type: 'object',
          properties: {
            title: { type: 'string', minLength: 1, maxLength: 500 },
            description: { type: 'string', maxLength: 5000 },
            type: { type: 'string', enum: ['task', 'project'] },
            status: { type: 'string', enum: ['pending', 'in_progress', 'on_hold', 'done', 'abandoned'] },
            visibility: { type: 'string', enum: ['private', 'group', 'public'] },
            groupIds: { type: 'array', items: { type: 'string' } },
            blockedBy: { type: 'array', items: { type: 'string' } },
            parentId: { type: 'string', nullable: true },
            deadline: { type: 'string', format: 'date-time', nullable: true },
            recurrence: {
              type: 'object',
              nullable: true,
              properties: {
                freq: { type: 'string', enum: ['daily', 'weekly', 'monthly', 'yearly'] },
                interval: { type: 'integer', minimum: 1 },
                until: { type: 'string', format: 'date-time' },
                count: { type: 'integer', minimum: 1 },
                byDay: { type: 'array', items: { type: 'string', enum: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'] } },
              },
            },
            metadata: { type: 'object', nullable: true },
            tags: { type: 'array', items: { type: 'string' } },
            pinned: { type: 'boolean' },
          },
        },
        Group: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            ownerId: { type: 'string' },
            name: { type: 'string' },
            members: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  userId: { type: 'string' },
                  role: { type: 'string', enum: ['editor', 'viewer'] },
                  username: { type: 'string' },
                  name: { type: 'string' },
                },
              },
            },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Account: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            name: { type: 'string' },
            provider: { type: 'string' },
            parentAccountId: { type: 'string', nullable: true },
            url: { type: 'string' },
            username: { type: 'string' },
            notes: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            credentials: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  key: { type: 'string' },
                  secretId: { type: 'string' },
                },
              },
            },
            accountId: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Domain: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            name: { type: 'string' },
            projectId: { type: 'string', nullable: true },
            registrarAccountId: { type: 'string', nullable: true },
            dnsAccountId: { type: 'string', nullable: true },
            expiryDate: { type: 'string', format: 'date-time', nullable: true },
            autoRenew: { type: 'boolean' },
            nameservers: { type: 'array', items: { type: 'string' } },
            sslProvider: { type: 'string' },
            notes: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Database: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            name: { type: 'string' },
            type: { type: 'string', enum: ['mongodb', 'postgres', 'mysql', 'redis', 'sqlite', 'other'] },
            secretId: { type: 'string', nullable: true },
            host: { type: 'string' },
            port: { type: 'integer', nullable: true },
            databaseName: { type: 'string' },
            backupEnabled: { type: 'boolean' },
            backupRetentionDays: { type: 'integer' },
            backupFrequency: { type: 'string', enum: ['hourly', '6hours', 'daily', 'weekly'] },
            lastBackupAt: { type: 'string', format: 'date-time', nullable: true },
            accountId: { type: 'string', nullable: true },
            tags: { type: 'array', items: { type: 'string' } },
            notes: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        BackupHistory: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            databaseId: { type: 'string' },
            userId: { type: 'string' },
            status: { type: 'string', enum: ['success', 'failed', 'partial'] },
            startedAt: { type: 'string', format: 'date-time' },
            completedAt: { type: 'string', format: 'date-time' },
            durationMs: { type: 'integer' },
            sizeBytes: { type: 'integer' },
            s3Path: { type: 'string' },
            s3Bucket: { type: 'string' },
            errorMessage: { type: 'string' },
            metadata: { type: 'object' },
            triggeredBy: { type: 'string' },
            lambdaRequestId: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Secret: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            name: { type: 'string' },
            description: { type: 'string' },
            type: { type: 'string', enum: ['connection_string', 'password', 'api_key', 'token', 'certificate', 'ssh_key', 'other'] },
            provider: { type: 'string', enum: ['bitwarden', 'bitwarden_sm', 'aws_secrets', '1password', 'vault', 'lastpass', 'custom', 'client_encrypted'] },
            providerSecretId: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            expiresAt: { type: 'string', format: 'date-time', nullable: true },
            lastRotatedAt: { type: 'string', format: 'date-time' },
            lastAccessedAt: { type: 'string', format: 'date-time' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Subscription: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            name: { type: 'string' },
            provider: { type: 'string' },
            amount: { type: 'number' },
            currency: { type: 'string' },
            billingCycle: { type: 'string' },
            nextBillingDate: { type: 'string', format: 'date-time', nullable: true },
            expiryDate: { type: 'string', format: 'date-time', nullable: true },
            autoRenew: { type: 'boolean' },
            status: { type: 'string' },
            category: { type: 'string' },
            paymentMethod: { type: 'string' },
            url: { type: 'string' },
            notes: { type: 'string' },
            tags: { type: 'array', items: { type: 'string' } },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Knowledge: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            userId: { type: 'string' },
            content: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Context: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            key: { type: 'string' },
            value: { type: 'string' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
  },
  apis: ['./src/routes/*.ts'],
});

export default spec;
