import { IUserRepository } from './interfaces/IUserRepository';
import { ITaskRepository } from './interfaces/ITaskRepository';
import { IAccountRepository } from './interfaces/IAccountRepository';
import { IGroupRepository } from './interfaces/IGroupRepository';
import { ISecretRepository } from './interfaces/ISecretRepository';
import { IDomainRepository } from './interfaces/IDomainRepository';
import { IDatabaseRepository } from './interfaces/IDatabaseRepository';
import { ISubscriptionRepository } from './interfaces/ISubscriptionRepository';
import { IKnowledgeRepository } from './interfaces/IKnowledgeRepository';
import { IContextRepository } from './interfaces/IContextRepository';
import { IBackupHistoryRepository } from './interfaces/IBackupHistoryRepository';
import { IRecurrenceExceptionRepository } from './interfaces/IRecurrenceExceptionRepository';

import { MongoUserRepository } from './mongodb/MongoUserRepository';
import { MongoTaskRepository } from './mongodb/MongoTaskRepository';
import { MongoAccountRepository } from './mongodb/MongoAccountRepository';
import { MongoGroupRepository } from './mongodb/MongoGroupRepository';
import { MongoSecretRepository } from './mongodb/MongoSecretRepository';
import { MongoDomainRepository } from './mongodb/MongoDomainRepository';
import { MongoDatabaseRepository } from './mongodb/MongoDatabaseRepository';
import { MongoSubscriptionRepository } from './mongodb/MongoSubscriptionRepository';
import { MongoKnowledgeRepository } from './mongodb/MongoKnowledgeRepository';
import { MongoContextRepository } from './mongodb/MongoContextRepository';
import { MongoBackupHistoryRepository } from './mongodb/MongoBackupHistoryRepository';
import { MongoRecurrenceExceptionRepository } from './mongodb/MongoRecurrenceExceptionRepository';

import { Neo4jUserRepository } from './neo4j/Neo4jUserRepository';
import { Neo4jTaskRepository } from './neo4j/Neo4jTaskRepository';
import { Neo4jAccountRepository } from './neo4j/Neo4jAccountRepository';
import { Neo4jGroupRepository } from './neo4j/Neo4jGroupRepository';
import { Neo4jSecretRepository } from './neo4j/Neo4jSecretRepository';
import { Neo4jDomainRepository } from './neo4j/Neo4jDomainRepository';
import { Neo4jDatabaseRepository } from './neo4j/Neo4jDatabaseRepository';
import { Neo4jSubscriptionRepository } from './neo4j/Neo4jSubscriptionRepository';
import { Neo4jKnowledgeRepository } from './neo4j/Neo4jKnowledgeRepository';
import { Neo4jContextRepository } from './neo4j/Neo4jContextRepository';
import { Neo4jBackupHistoryRepository } from './neo4j/Neo4jBackupHistoryRepository';
import { Neo4jRecurrenceExceptionRepository } from './neo4j/Neo4jRecurrenceExceptionRepository';

const engine = process.env.DB_ENGINE || 'mongodb';
const isNeo4j = engine === 'neo4j';

export const userRepo: IUserRepository = isNeo4j ? new Neo4jUserRepository() : new MongoUserRepository();
export const taskRepo: ITaskRepository = isNeo4j ? new Neo4jTaskRepository() : new MongoTaskRepository();
export const accountRepo: IAccountRepository = isNeo4j ? new Neo4jAccountRepository() : new MongoAccountRepository();
export const groupRepo: IGroupRepository = isNeo4j ? new Neo4jGroupRepository() : new MongoGroupRepository();
export const secretRepo: ISecretRepository = isNeo4j ? new Neo4jSecretRepository() : new MongoSecretRepository();
export const domainRepo: IDomainRepository = isNeo4j ? new Neo4jDomainRepository() : new MongoDomainRepository();
export const databaseRepo: IDatabaseRepository = isNeo4j ? new Neo4jDatabaseRepository() : new MongoDatabaseRepository();
export const subscriptionRepo: ISubscriptionRepository = isNeo4j ? new Neo4jSubscriptionRepository() : new MongoSubscriptionRepository();
export const knowledgeRepo: IKnowledgeRepository = isNeo4j ? new Neo4jKnowledgeRepository() : new MongoKnowledgeRepository();
export const contextRepo: IContextRepository = isNeo4j ? new Neo4jContextRepository() : new MongoContextRepository();
export const backupHistoryRepo: IBackupHistoryRepository = isNeo4j ? new Neo4jBackupHistoryRepository() : new MongoBackupHistoryRepository();
export const recurrenceExceptionRepo: IRecurrenceExceptionRepository = isNeo4j ? new Neo4jRecurrenceExceptionRepository() : new MongoRecurrenceExceptionRepository();
